### ISSUE TITLE
mxnet version?

### ISSUE THREAD

**Issue by Hjy20255** [buptweixin/mxnet-deeplab#1]
Hi～～～
my mxnet 0.9.3  can  not  run  your  code  .
can you tell  me  your  version?

**Comment by buptweixin** [comment]
My mxnet's version is 0.9.4, but I think this code should also be supported by your version. 
Can you show me your error report?

**Comment by Hjy20255** [comment]
Thank you for your reply ！
But 0.9.4?  new version is 0.9.3 in https://github.com/dmlc/mxnet/
my error：
INFO:root:Namespace(retrain=False, root='./ISPRS')
[18:22:30] src/nnvm/legacy_json_util.cc:153: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
Traceback (most recent call last):
  File "/home/hjy/mxnet-deeplab/deeplab.py", line 73, in <module>
    main()
  File "/home/hjy/mxnet-deeplab/deeplab.py", line 25, in main
    deeplabv2_symbol_train = symbol_deeplab.get_deeplab_symbol_train()
  File "/home/hjy/mxnet-deeplab/symbol_deeplab.py", line 123, in get_deeplab_symbol_train
    pool5 = vgg_16(data, workspace_default)
  File "/home/hjy/mxnet-deeplab/symbol_deeplab.py", line 14, in vgg_16
    name="conv1_1")
  File "mxnet/cython/symbol.pyx", line 151, in symbol._make_atomic_symbol_function.creator (mxnet/cython/symbol.cpp:3591)
  File "mxnet/cython/base.pyi", line 36, in symbol.CALL (mxnet/cython/symbol.cpp:1624)
mxnet.base.MXNetError: setting variable attributes with weight_lr_mult is deprecated. please instead use
w = Variable(lr_mult=1)
sym = YourSymbolName(weight=w)

**Comment by buptweixin** [comment]
Oh! I made a mistake. My version was v0.7. In fact, the json format had changed, so you should use my version.
